# 1. Build stage
FROM node:22-alpine AS build

# Install git
RUN apk add --no-cache git

# Clone the repository
RUN git clone https://github.com/mayberryjp/sando-website.git /app

# Set working directory
WORKDIR /app

RUN echo "VITE_API_BASE_URL=SANDO_API_BASE_URL" >>/app/.env

# Install dependencies and build the Vite project
RUN npm install --silent && npx vite build


# 2. Production stage
FROM nginx:stable-alpine

# Copy built assets from the build stage (Vite builds to /dist by default)
COPY --from=build /app/dist /usr/share/nginx/html

# Copy nginx config from the cloned repo
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf

# Expose custom port
EXPOSE 3030

COPY --from=build /app/env.sh /docker-entrypoint.d/env.sh
RUN chmod +x /docker-entrypoint.d/env.sh

# Default command
CMD ["nginx", "-g", "daemon off;"]